name: Generate GeoJSON

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate GeoJSON
        run: |
          python generate_vacdm_geojson.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*.geojson"
          commit_message: "Generate GeoJSON"
          commit_options: "--no-verify"
          branch: ${{ github.ref }}
